name: CD Pipeline

on:
  push:
    branches:
      - main  # Triggers only when changes are pushed to main (which happens when a PR is merged)

jobs:
  deploy:
    name: deploy  # Ensures job is named exactly "deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2 Ubuntu Instance via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}       # Your EC2 public IP or hostname (e.g., 16.171.62.35)
          username: ${{ secrets.EC2_USER }}   # EC2 username (commonly "ubuntu")
          key: ${{ secrets.EC2_SSH_KEY }}     # Your private SSH key (stored as a secret)
          port: 22
          script: |
            # Update package lists and install Docker and Git
            sudo apt update -y
            sudo apt install -y docker.io git

            # Navigate to your FastAPI project directory
            cd /path/to/your/project

            # Pull latest changes from the main branch
            git pull origin main

            # Rebuild and restart Docker containers
            sudo docker-compose down
            sudo docker-compose up -d --build

            # Restart Nginx to apply changes
            sudo systemctl restart nginx
